# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=20, unique=True)),
                ('hostname', models.CharField(max_length=16, unique=True)),
                ('loopback', models.CharField(max_length=16)),
                ('macaddress', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': 'Manage Router',
            },
        ),
    ]
